k = State of nauture

n = Number of risky assets

Y = k X 1 vector of desired final payoffs in each state of nature

N = k X 1 vector of required shares in each asset in order to create portfolio with payoffs of Y

X = k x n matrix that shows all possible outcomes of final payoffs

P = k X 1 vector of initial prices for one share of each asset

es = k X 1 vector of final payoffs for elementary security that delivers final payoff of one in state s and zero in every other state

ps = state price for state s, which represents initial value of receiving final payoff of one in state s

# Lesson 1

Expected Utility functions
Risk Aversion
Normal Returns
Indifference Curve

# Lesson 2

Efficient Frontier
Constant Absolute Risk Aversion

# Lesson 3

CAPM
Security Market Line
Pricing Abnomolies

# Lesson 4

Multi-Factor Models
Downside beta
Performance Measurement - Sharpe/Sortino/Treynor

# Lesson 5

Black-Litterman
Skewness
Three Moment CAPM

# Lesson 6

Consumption CAPM
Hansen-Jagannathan Bound
Power Utility of Consumption -> Investor has constant coefficient of risk aversion, measured by gamma
Rare Disasters

# Lesson 7

Multi-Asset Pricing
Endowment Economy -> Aggregate output grows randomly over time
Price - Dividend Ratio
Rare disasters is not an acceptable solution to equity premium puzzle in a multi-period endowment economy with complete market and investors with constant relative risk aversion.


# Lesson 8

Prospect Theory
Price - Dividend Ratio
Equity premium increases as utility from recent financial gain or loss makes bigger contribution, but it is still too small for reasonable level of risk aversion and loss aversion.
House money effect, where investors are more willing to gamble after prior gains and less willing to gamble after prior losses. Even allowing investors to keep track of accumulated financial gain or loss over entire lifetime, the annual equity premium is about 4.1%, which is only about half as big as seen in real-life. So prospect theory combined with house money effect is still insufficient to explain real world equity risk premium. 


In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

# Datetime
import datetime as dt
from datetime import datetime
from datetime import timedelta

import warnings

# Binomial Model - 1 risky asset, 1 riskless asset

In [2]:
Initial_price_stock = 6

Final_payoff_good = 10
Final_payoff_bad = 5

Riskfree_rate = 1.05

In [3]:
# Vector of initial prices for one share of each asset

P = [Initial_price_stock, 1/Riskfree_rate]

P = pd.DataFrame(P)

In [4]:
P

0
0  6.000000
1  0.952381

In [5]:
# Define Stock_payoff as an array with floats instead of lists
Stock_payoff = np.array([Final_payoff_good, Final_payoff_bad], dtype=float)

# Define Bond_payoff as a 2D array with floats
Bond_payoff = np.ones((len(Stock_payoff), 1), dtype=float)

# Combine both arrays into a single array
X = np.column_stack((Stock_payoff, Bond_payoff))

# Create a DataFrame and ensure all values are floats
X = pd.DataFrame(X, columns=['Stock_payoff', 'Bond_payoff'])

In [6]:
# Final payoff of every asset in every state

X

Stock_payoff  Bond_payoff
0          10.0          1.0
1           5.0          1.0

In [7]:
# Slide 9
# Initial value of receiving final payoff of 1 in state s

Vector_of_state_prices = P.T.dot(np.linalg.inv(X))

In [8]:
# initial value of receiving final payoff of one in good state,  initial value of receiving final payoff of one in bad state

# what you have to pay at time 0 to obtain 1 unit of output in the first state, what you have to pay at time 0 to obtain 1 unit of output in the second state

Vector_of_state_prices

0         1
0  0.247619  0.704762

In [9]:
Vector_of_risk_neutral_probabilities = Vector_of_state_prices * Riskfree_rate

In [10]:
Vector_of_risk_neutral_probabilities

0     1
0  0.26  0.74

### Call option example

In [11]:
Strike_price = 6

In [12]:
Initial_price_call_option = \
    (
        Vector_of_risk_neutral_probabilities.iloc[0,0] * max(0,Final_payoff_good - Strike_price) / Riskfree_rate 
        +
        Vector_of_risk_neutral_probabilities.iloc[0,1] * max(0,Final_payoff_bad - Strike_price) / Riskfree_rate 
    )

In [13]:
Initial_price_call_option

0.9904761904761913

In [14]:
Initial_price_put_option = \
    (
        Vector_of_risk_neutral_probabilities.iloc[0,0] * max(0,Strike_price - Final_payoff_good) / Riskfree_rate 
        +
        Vector_of_risk_neutral_probabilities.iloc[0,1] * max(0,Strike_price - Final_payoff_bad) / Riskfree_rate 
    )

In [15]:
Initial_price_put_option 

0.7047619047619045

### If we want a desired final payoff in the Binomial example

We can create unique portfolios to deliver any set of desired payoffs, or replicate payoffs for any existing investment

In [16]:
Y = [100, 100]

Y = pd.DataFrame(Y)

In [17]:
N = np.linalg.inv(X).dot(Y)

In [18]:
N

array([[-1.11022302e-15],
       [ 1.00000000e+02]])

In [19]:
Initial_price_portfolio = Vector_of_state_prices.dot(Y)

In [20]:
Initial_price_portfolio

0
0  95.238095

# State Prices

In [21]:
# Set Riskfree_rate

Riskfree_rate = 1.1

Initial_price_stockA = 45
Initial_price_stockB = 45
#Initial_price_stockC = 45

State_Probability = [0.3,0.5,0.2]

# Final share price after one year

Asset_A=[75,55,20]
Asset_B=[60,50,40]
#Asset_C=[3,4,5]

In [22]:
# Vector of initial prices for one share of each asset

P = [1/Riskfree_rate,Initial_price_stockA,Initial_price_stockB]

P = pd.DataFrame(P)

In [23]:
P

0
0   0.909091
1  45.000000
2  45.000000

In [24]:
# Define Stock_payoff as an array with floats instead of lists
Stock_payoffA = np.array(Asset_A, dtype=float)

Stock_payoffB = np.array(Asset_B, dtype=float)

#Stock_payoffC = np.array(Asset_C, dtype=float)

# Define Bond_payoff as a 2D array with floats
Bond_payoff = np.ones((len(Stock_payoffA), 1), dtype=float)

# Combine both arrays into a single array
X = np.column_stack((Bond_payoff, Stock_payoffA, Stock_payoffB))

# Create a DataFrame and ensure all values are floats
X = pd.DataFrame(X, columns=['Bond_payoff', 'Stock_payoffA', 'Stock_payoffB'])

In [25]:
Stock_payoffA 

array([75., 55., 20.])

In [26]:
# Final payoff of every asset in every state

X

Bond_payoff  Stock_payoffA  Stock_payoffB
0          1.0           75.0           60.0
1          1.0           55.0           50.0
2          1.0           20.0           40.0

In [27]:
# Slide 9
# Initial value of receiving final payoff of 1 in state s

Vector_of_state_prices = P.T.dot(np.linalg.inv(X))

In [28]:
Vector_of_state_prices

0         1         2
0  0.227273  0.409091  0.272727

In [29]:
Vector_of_risk_neutral_probabilities = Vector_of_state_prices * Riskfree_rate

In [30]:
Vector_of_risk_neutral_probabilities

0     1    2
0  0.25  0.45  0.3

### Call option example

Option to buy one share of Stock A and one share of Stock B for 100

In [31]:
Strike_price = 100

In [32]:
Initial_price_call_option = \
    (
        (Vector_of_risk_neutral_probabilities.iloc[0,0] * max(0,Stock_payoffA[0] + Stock_payoffB[0] - Strike_price) / Riskfree_rate)
        +
        (Vector_of_risk_neutral_probabilities.iloc[0,1] * max(0,Stock_payoffA[1] + Stock_payoffB[1] - Strike_price) / Riskfree_rate)
        +
        (Vector_of_risk_neutral_probabilities.iloc[0,2] * max(0,Stock_payoffA[2] + Stock_payoffB[2] - Strike_price) / Riskfree_rate)
    )

In [33]:
Initial_price_call_option

10.000000000000025

In [34]:
Initial_price_put_option = \
    (
        (Vector_of_risk_neutral_probabilities.iloc[0,0] * max(0,Strike_price -(Stock_payoffA[0] + Stock_payoffB[0])) / Riskfree_rate)
        +
        (Vector_of_risk_neutral_probabilities.iloc[0,1] * max(0,Strike_price -(Stock_payoffA[1] + Stock_payoffB[1])) / Riskfree_rate)
        +
        (Vector_of_risk_neutral_probabilities.iloc[0,2] * max(0,Strike_price -(Stock_payoffA[2] + Stock_payoffB[2])) / Riskfree_rate)
    )

In [35]:
Initial_price_put_option

10.90909090909091

### If we want a desired final payoff in the State prices example

In [36]:
Y = [100, 100, 100]

Y = pd.DataFrame(Y)

In [37]:
N = np.linalg.inv(X).dot(Y)

In [38]:
N

array([[ 1.00000000e+02],
       [-4.99600361e-16],
       [-1.55431223e-15]])

In [39]:
Initial_price_portfolio = Vector_of_state_prices.dot(Y)

In [40]:
Initial_price_portfolio

0
0  90.909091