Session 5 Slides 3-9

In [1]:
import matplotlib.pyplot as plt
from matplotlib.pyplot import subplot, scatter, plot, axis
import numpy as np
import pandas as pd
import seaborn as sns
from scipy import stats
import statsmodels.api as sm

# Datetime
import datetime as dt
from datetime import datetime
from datetime import timedelta

import warnings
warnings.filterwarnings("ignore")

3 risky assets

Investor expects annual risk premium of 5% for first asset

Expects second asset to outperform third asset by 1%

In [2]:
# pi = sample risk premiums

pi = np.array([0.05, 0.05, 0.05])

In [3]:
# V = covariance matrix of excess returns

V = pd.DataFrame(np.random.uniform(0, 1, size=(3, 3)), index=[0, 1, 2], columns=[0, 1, 2]).values

In [4]:
V

array([[0.15750666, 0.75006338, 0.30917005],
       [0.84312175, 0.90070198, 0.24829728],
       [0.49821258, 0.17300773, 0.07003742]])

In [ ]:
# Omega = covariance matrix based on confidence of investors views
# Omega is an identity matrix equal to the number of views an investor has

Omega = np.eye(2)

In [6]:
Omega

array([[1., 0.],
       [0., 1.]])

In [7]:
# m is the number of data points used to estimate the covariance matrix V

m = 50

theta = 1/m

In [8]:
# First Asset, Second Asset, Third Asset

First_view=[1,0,0]
Second_view=[0,1,-1]
#Third_view=[1,0,0]

In [9]:
# Views = P

Views = pd.DataFrame([First_view, Second_view], index=['First_view', 'Second_view']).values

In [10]:
# First row represents absolute view, weights sum to 1
# Second row represents relative view, weights sum to 0

Views

array([[ 1,  0,  0],
       [ 0,  1, -1]])

In [11]:
First_view_return=[0.05]
Second_view_return=[0.01]

In [12]:
# Return_Views = Q

#Return_Views = pd.DataFrame([First_view_return, Second_view_return], index=['First_view_return', 'Second_view_return'])

Return_Views = np.array([First_view_return, Second_view_return]).flatten() 

In [13]:
Return_Views

array([0.05, 0.01])

In [14]:
pi_hat = pi + theta * V @ Views.T @ np.linalg.inv(theta * Views @ V @ Views.T + Omega) @ (Return_Views - Views @ pi)

In [15]:
pi_hat

array([0.05008695, 0.0501276 , 0.05001951])

In [16]:
M = V + np.linalg.inv((1 / theta) * np.linalg.inv(V) + Views.T @ np.linalg.inv(Omega) @ Views)

In [17]:
M

array([[0.16058711, 0.76489189, 0.31530341],
       [0.85984348, 0.91827946, 0.25311434],
       [0.50813213, 0.17629069, 0.07136988]])

# Skewness

Risk averse investors faces trade off between minimising variance of returns versus maximizing skewnsess of returns.

We can identify frontier portfolios that minimize downside risk, for a given target mean return.

If frontier portfolios minimize below-target semi-variance, then tangency portfolio will maximise Sortino ratio.

Investors demand economic compensation for exposure to variance risk.

Investors demand economic compensation for exposure to negative skewness, but will pay for exposure to positive skewness.